########################################################################
# Pointwise - Proprietary software product of Pointwise, Inc.
#             Copyright (c) 1995-2014 Pointwise, Inc.
#             All rights reserved.
#
# module.mk for src\plugins\NUC3d plugin
########################################################################

########################################################################
########################################################################
#
#                   DO NOT EDIT THIS FILE
#
# To simplify SDK upgrades, the standard module.mk file should NOT be edited.
#
# If you want to modify a plugin's build process, you should rename
# modulelocal-sample.mk to modulelocal.mk and edit its settings.
#
# See the comments in modulelocal-sample.mk for more information.
#
#                   DO NOT EDIT THIS FILE
#
########################################################################
########################################################################

NUC3d_LOC := $(PLUGINS_LOC)/NUC3d
NUC3d_LIB := NUC3d$(DBG_SUFFIX)
NUC3d_CXX_LOC := $(NUC3d_LOC)
NUC3d_OBJ_LOC := $(PLUGINS_OBJ_LOC)/NUC3d

NUC3d_FULLNAME := lib$(NUC3d_LIB).$(SHLIB_SUFFIX)
NUC3d_FULLLIB := $(PLUGINS_DIST_DIR)/$(NUC3d_FULLNAME)

NUC3d_DEPS = \
    $(NULL)

MODCXXFILES := \
    runtimeWrite.cxx \
    $(NULL)

# IMPORTANT:
# Must recompile the shared/XXX/.cxx files for each plugin. These .cxx files
# include the plugin specific settings defined in the ./NUC3d/*.h
# files.
NUC3d_SRC := \
    $(PLUGINS_RT_PWPSRC) \
    $(PLUGINS_RT_PWGMSRC) \
    $(PLUGINS_RT_CAEPSRC) \
    $(patsubst %,$(NUC3d_CXX_LOC)/%,$(MODCXXFILES))

NUC3d_SRC_CXX := $(filter %.cxx,$(MODCXXFILES))

# place the .o files generated from shared sources in the plugin's
# OBJ folder.
NUC3d_OBJ := \
    $(patsubst %.cxx,$(NUC3d_OBJ_LOC)/%.o,$(PLUGINS_RT_PWPFILES)) \
    $(patsubst %.cxx,$(NUC3d_OBJ_LOC)/%.o,$(PLUGINS_RT_PWGMFILES)) \
    $(patsubst %.cxx,$(NUC3d_OBJ_LOC)/%.o,$(PLUGINS_RT_CAEPFILES)) \
    $(patsubst %.cxx,$(NUC3d_OBJ_LOC)/%.o,$(NUC3d_SRC_CXX)) \
    $(NULL)

# To allow over-rides, search FIRST for headers in the local module's folder.
# For example, a site.h file in the local module's folder will preempt the
# file .../src/plugins/site.h
NUC3d_INCL = \
    -I$(NUC3d_LOC) \
    $(PLUGINS_RT_INCL) \
    $(NULL)

NUC3d_LIBS = \
    $(NULL)

NUC3d_MAINT_TARGETS := \
    NUC3d_info \
    NUC3d_install \
    NUC3d_installnow \
    NUC3d_uninstall


########################################################################
# Get (OPTIONAL) locally defined make targets. If a plugin developer wants
# to extend a plugin's make scheme, they should create a modulelocal.mk file
# in the plugin's base folder. To provide for future SDK upgrades, the standard
# module.mk file should NOT be directly edited.
#
ifneq ($(wildcard $(NUC3d_LOC)/modulelocal.mk),)
    NUC3d_DEPS += $(NUC3d_LOC)/modulelocal.mk

    include $(NUC3d_LOC)/modulelocal.mk

    # merge in plugin private settings
    NUC3d_OBJ += \
        $(patsubst %.cxx,$(NUC3d_OBJ_LOC)/%.o,$(filter %.cxx,$(NUC3d_CXXFILES_PRIVATE))) \
        $(NULL)

    NUC3d_SRC += \
        $(patsubst %,$(NUC3d_CXX_LOC)/%,$(NUC3d_CXXFILES_PRIVATE)) \
        $(NULL)

    NUC3d_INCL += $(NUC3d_INCL_PRIVATE)
    NUC3d_LIBS += $(NUC3d_LIBS_PRIVATE)
    NUC3d_CXXFLAGS += $(NUC3d_CXXFLAGS_PRIVATE)
    NUC3d_LDFLAGS += $(NUC3d_LDFLAGS_PRIVATE)
    NUC3d_MAINT_TARGETS += $(NUC3d_MAINT_TARGETS_PRIVATE)
    NUC3d_DEPS += $(NUC3d_DEPS_PRIVATE)
endif

PLUGIN_MAINT_TARGETS += $(NUC3d_MAINT_TARGETS)
PLUGIN_OBJ += $(NUC3d_OBJ)

# add to plugin maint targets to the global .PHONY target
.PHONY: \
    $(NUC3d_MAINT_TARGETS) \
    $(NULL)


########################################################################
# Set the final build macros
NUC3d_CXXFLAGS += $(CXXFLAGS) $(PLUGINS_STDDEFS) $(NUC3d_INCL) \
    -DPWGM_HIDE_UNSTRUCTURED_API


ifeq ($(machine),macosx)
NUC3d_LDFLAGS += -install_name "@rpath/Plugins/$(NUC3d_FULLNAME)"
else
NUC3d_LDFLAGS +=
endif


########################################################################
# list of plugin's build targets
#
NUC3d: $(NUC3d_FULLLIB)

$(NUC3d_FULLLIB): $(NUC3d_OBJ) $(NUC3d_DEPS)
	@echo "***"
	@echo "*** $@"
	@echo "***"
	@mkdir -p $(dir $@)
	$(SHLIB_LD) $(ARCH_FLAGS) $(NUC3d_LDFLAGS) -o $(NUC3d_FULLLIB) $(NUC3d_OBJ) $(NUC3d_LIBS) $(SYS_LIBS)

NUC3d_info:
	@echo ""
	@echo "--------------------------------------------------------------"
ifeq ($(machine),macosx)
	otool -L -arch all $(NUC3d_FULLLIB)
	@echo ""
endif
	file $(NUC3d_FULLLIB)
	@echo "--------------------------------------------------------------"
	@echo ""


########################################################################
# list of plugin's intermediate targets
#
$(NUC3d_OBJ_LOC):
	mkdir -p $(NUC3d_OBJ_LOC)

#.......................................................................
# build .d files for the plugin and each of the shared runtime sources
# the .d files will be placed in the plugins OBJ folder NUC3d_OBJ_LOC
$(NUC3d_OBJ_LOC)/%.d: $(NUC3d_CXX_LOC)/%.cxx
	@echo "Updating dependencies $(NUC3d_OBJ_LOC)/$*.d"
	@mkdir -p $(dir $@)
	@./depend.sh $(NUC3d_OBJ_LOC) $(NUC3d_CXXFLAGS) $< > $@

$(NUC3d_OBJ_LOC)/%.d: $(PLUGINS_RT_PWPLOC)/%.cxx
	@echo "Updating dependencies $(NUC3d_OBJ_LOC)/$*.d"
	@mkdir -p $(dir $@)
	@./depend.sh $(NUC3d_OBJ_LOC) $(NUC3d_CXXFLAGS) $< > $@

$(NUC3d_OBJ_LOC)/%.d: $(PLUGINS_RT_PWGMLOC)/%.cxx
	@echo "Updating dependencies $(NUC3d_OBJ_LOC)/$*.d"
	@mkdir -p $(dir $@)
	@./depend.sh $(NUC3d_OBJ_LOC) $(NUC3d_CXXFLAGS) $< > $@

$(NUC3d_OBJ_LOC)/%.d: $(PLUGINS_RT_CAEPLOC)/%.cxx
	@echo "Updating dependencies $(NUC3d_OBJ_LOC)/$*.d"
	@mkdir -p $(dir $@)
	@./depend.sh $(NUC3d_OBJ_LOC) $(NUC3d_CXXFLAGS) $< > $@

#.......................................................................
# build .o files for the plugin and each of the shared runtime sources.
# the .o files will be placed in the plugins OBJ folder NUC3d_OBJ_LOC
$(NUC3d_OBJ_LOC)/%.o: $(NUC3d_CXX_LOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(dir $@)
	$(CXX) $(NUC3d_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<

$(NUC3d_OBJ_LOC)/%.o: $(PLUGINS_RT_PWPLOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(dir $@)
	$(CXX) $(NUC3d_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<

$(NUC3d_OBJ_LOC)/%.o: $(PLUGINS_RT_PWGMLOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(dir $@)
	$(CXX) $(NUC3d_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<

$(NUC3d_OBJ_LOC)/%.o: $(PLUGINS_RT_CAEPLOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(dir $@)
	$(CXX) $(NUC3d_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<


########################################################################
# list of plugin's clean targets
#
NUC3d_cleandep:
	-$(RMR) $(NUC3d_OBJ_LOC)/*.d

NUC3d_clean:
	-$(RMR) $(NUC3d_OBJ_LOC)/*.{d,o}

NUC3d_distclean: NUC3d_clean
	-$(RMF) $(NUC3d_FULLLIB) > /dev/null 2>&1

NUC3d_clobber:
	-$(RMR) $(NUC3d_OBJ_LOC)


########################################################################
# list of plugin's clean targets
#
NUC3d_install: install_validate NUC3d_installnow
	@echo "NUC3d Installed to '$(PLUGIN_INSTALL_FULLPATH)'"

NUC3d_installnow:
	-@$(CP) $(NUC3d_FULLLIB) "$(PLUGIN_INSTALL_FULLPATH)/libNUC3d.$(SHLIB_SUFFIX)"

NUC3d_uninstall:
	@echo "NUC3d Uninstalled from '$(PLUGIN_INSTALL_FULLPATH)'"
	-@$(RMF) "$(PLUGIN_INSTALL_FULLPATH)/libNUC3d.$(SHLIB_SUFFIX)"
